---
- name: "Test playbook run"
  hosts: all
  tasks:
    - name: "Debug"
      ansible.builtin.debug:
        msg: "Test debug"
---
- name: "Test Ping"
  hosts: all
  become: no
  tasks:
    - name: ping
      ping:
