---
- name: "Test playbook run"
  hosts: all
  tasks:
    - name: "Debug"
      ansible.builtin.debug:
        msg: "Test debug"

- name: Testping
  hosts: all
  tasks:
    - name: ping
      become: no
      ping:
